// Generated by scripts/build-tokens.mjs — do not edit.
package app.rounds.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object RoundsColors {
    val bgCanvas = Color(0xFF06070B)
    val bgElevated = Color(0xFF0E1017)
    val surfacePrimary = Color(0xFF151A24)
    val surfaceSecondary = Color(0xFF1C2230)
    val surfaceTertiary = Color(0xFF262E3D)
    val labelPrimary = Color(0xFFFFFFFF)
    val labelSecondary = Color(0x99EBEBF5)
    val labelTertiary = Color(0x4DEBEBF5)
    val labelQuaternary = Color(0x2EEBEBF5)
    val separator = Color(0x17FFFFFF)
    val brandTint = Color(0xFF3B82F6)
    val brandTintDeep = Color(0xFF1D4ED8)
    val brandTintLight = Color(0xFF7CB3FF)
    val paceEasy = Color(0xFF7CB3FF)
    val paceSteady = Color(0xFF30D158)
    val paceQuick = Color(0xFFFF9F0A)
    val paceSlowDown = Color(0xFFFF453A)
    val safety = Color(0xFFFF453A)
    val success = Color(0xFF30D158)
    val warning = Color(0xFFFF9F0A)
    val night1 = Color(0xFF3B82F6)
    val night2 = Color(0xFF8B5CF6)
    val night3 = Color(0xFFF43F5E)
    val night4 = Color(0xFFFB923C)
    val glassFillFrom = Color(0x2BFFFFFF)
    val glassFillTo = Color(0x0FFFFFFF)
    val glassRimFrom = Color(0x57FFFFFF)
    val glassRimTo = Color(0x0FFFFFFF)
    val glassInnerHighlight = Color(0x4DFFFFFF)
    val glassInnerShade = Color(0x59000000)
    val cardRim = Color(0x14FFFFFF)
    val cardSheenFrom = Color(0x13FFFFFF)
    val cardSheenTo = Color(0x00FFFFFF)
    val transparent = Color(0xFFFFFFFF)
}

object RoundsRadius {
    val control = 14.dp
    val button = 20.dp
    val card = 22.dp
    val cardLg = 26.dp
    val sheet = 44.dp
    val device = 55.dp
    val capsule = 999.dp
}

object RoundsSpace {
    val xxs = 2.dp
    val xs = 4.dp
    val s = 6.dp
    val sm = 8.dp
    val m = 12.dp
    val md = 16.dp
    val lg = 20.dp
    val xl = 24.dp
    val xxl = 32.dp
    val xxxl = 40.dp
}
