// Generated by scripts/build-tokens.mjs — do not edit.
// Used by the Live Activity, the widgets and the Watch app so the native
// surfaces cannot drift from the app.
import SwiftUI

public enum ROUNDS {
  public enum Colors {
    static let bgCanvas = Color(hex: "#06070B")
    static let bgElevated = Color(hex: "#0E1017")
    static let surfacePrimary = Color(hex: "#151A24")
    static let surfaceSecondary = Color(hex: "#1C2230")
    static let surfaceTertiary = Color(hex: "#262E3D")
    static let labelPrimary = Color(hex: "#FFFFFF")
    static let labelSecondary = Color(.sRGB, red: 0.9216, green: 0.9216, blue: 0.9608, opacity: 0.6)
    static let labelTertiary = Color(.sRGB, red: 0.9216, green: 0.9216, blue: 0.9608, opacity: 0.3)
    static let labelQuaternary = Color(.sRGB, red: 0.9216, green: 0.9216, blue: 0.9608, opacity: 0.18)
    static let separator = Color(.sRGB, red: 1.0000, green: 1.0000, blue: 1.0000, opacity: 0.09)
    static let brandTint = Color(hex: "#3B82F6")
    static let brandTintDeep = Color(hex: "#1D4ED8")
    static let brandTintLight = Color(hex: "#7CB3FF")
    static let paceEasy = Color(hex: "#7CB3FF")
    static let paceSteady = Color(hex: "#30D158")
    static let paceQuick = Color(hex: "#FF9F0A")
    static let paceSlowDown = Color(hex: "#FF453A")
    static let safety = Color(hex: "#FF453A")
    static let success = Color(hex: "#30D158")
    static let warning = Color(hex: "#FF9F0A")
    static let night1 = Color(hex: "#3B82F6")
    static let night2 = Color(hex: "#8B5CF6")
    static let night3 = Color(hex: "#F43F5E")
    static let night4 = Color(hex: "#FB923C")
    static let glassFillFrom = Color(.sRGB, red: 1.0000, green: 1.0000, blue: 1.0000, opacity: 0.17)
    static let glassFillTo = Color(.sRGB, red: 1.0000, green: 1.0000, blue: 1.0000, opacity: 0.06)
    static let glassRimFrom = Color(.sRGB, red: 1.0000, green: 1.0000, blue: 1.0000, opacity: 0.34)
    static let glassRimTo = Color(.sRGB, red: 1.0000, green: 1.0000, blue: 1.0000, opacity: 0.06)
    static let glassInnerHighlight = Color(.sRGB, red: 1.0000, green: 1.0000, blue: 1.0000, opacity: 0.3)
    static let glassInnerShade = Color(.sRGB, red: 0.0000, green: 0.0000, blue: 0.0000, opacity: 0.35)
    static let cardRim = Color(.sRGB, red: 1.0000, green: 1.0000, blue: 1.0000, opacity: 0.08)
    static let cardSheenFrom = Color(.sRGB, red: 1.0000, green: 1.0000, blue: 1.0000, opacity: 0.075)
    static let cardSheenTo = Color(.sRGB, red: 1.0000, green: 1.0000, blue: 1.0000, opacity: 0)
    static let transparent = Color.clear
  }
  public enum Radius {
    static let control = CGFloat(14)
    static let button = CGFloat(20)
    static let card = CGFloat(22)
    static let cardLg = CGFloat(26)
    static let sheet = CGFloat(44)
    static let device = CGFloat(55)
    static let capsule = CGFloat(999)
  }
  public enum Space {
    static let xxs = CGFloat(2)
    static let xs = CGFloat(4)
    static let s = CGFloat(6)
    static let sm = CGFloat(8)
    static let m = CGFloat(12)
    static let md = CGFloat(16)
    static let lg = CGFloat(20)
    static let xl = CGFloat(24)
    static let xxl = CGFloat(32)
    static let xxxl = CGFloat(40)
  }
  /// Corner smoothing 0.6 — use RoundedRectangle(cornerRadius:style:.continuous)
  public static let cornerSmoothing = 0.6
}
