/**
 * Emits tokens.json (+ Swift and Kotlin constants) from the single source of
 * truth in src/design/tokens.ts.
 *
 * The point of generating rather than hand-maintaining these: a hex literal
 * that appears in two places will eventually disagree with itself, and the
 * native surfaces (Live Activity, widgets, Watch) are exactly where that
 * divergence is least visible and most embarrassing.
 *
 *   node scripts/build-tokens.mjs
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { execSync } from 'node:child_process';

const src = execSync(
  'npx esbuild src/design/tokens.ts --bundle --format=esm --platform=neutral',
  { encoding: 'utf8' }
);
const mod = await import('data:text/javascript;base64,' + Buffer.from(src).toString('base64'));
const { color, gradient, space, radius, geometry, type, glow, elevation, blur, motion } = mod;

const tokens = {
  $schema: 'https://design-tokens.github.io/community-group/format/',
  color: {
    bg: leaf(color.bg),
    surface: leaf(color.surface),
    label: leaf(color.label),
    brand: leaf(color.brand),
    pace: leaf(color.pace),
    night: Object.fromEntries(color.night.map((c, i) => [String(i + 1), { $type: 'color', $value: c }])),
    separator: { $type: 'color', $value: color.separator },
    safety: { $type: 'color', $value: color.safety },
  },
  gradient: Object.fromEntries(
    Object.entries(gradient).map(([k, v]) => [k, { $type: 'gradient', $value: v }])
  ),
  space: leaf(space, 'dimension'),
  radius: leaf(radius, 'dimension'),
  geometry: { $type: 'dimension', $value: geometry },
  type: Object.fromEntries(
    Object.entries(type).map(([k, v]) => [k, { $type: 'typography', $value: v }])
  ),
  /** Composite recipes — the parts you cannot express as a flat value. */
  recipe: {
    glass: {
      $type: 'composite',
      $value: {
        layer: 'functional-only',
        backgroundBlur: blur.glass,
        base: 'rgba(10,12,18,0.55)',
        fill: gradient.glassFill,
        rim: gradient.glassRim,
        innerHighlight: color.glass.innerHighlight,
        innerShade: color.glass.innerShade,
        shadow: elevation.glass,
      },
    },
    card: {
      $type: 'composite',
      $value: {
        layer: 'content-only',
        fill: color.surface.primary,
        blooms: 2,
        bloomOpacity: [0.3, 0.22],
        sheen: gradient.cardSheen,
        rim: color.card.rim,
        shadow: elevation.card,
      },
    },
    glow: { $type: 'composite', $value: { core: glow.core, halo: glow.halo, limit: 'one control per screen' } },
  },
  motion: leaf(motion, 'duration'),
};

function leaf(obj, $type = 'color') {
  return Object.fromEntries(Object.entries(obj).map(([k, v]) => [k, { $type, $value: v }]));
}

mkdirSync('tokens', { recursive: true });
writeFileSync('tokens/tokens.json', JSON.stringify(tokens, null, 2) + '\n');

/* ---- NativeWind theme ---- */
writeFileSync(
  'tokens/nativewind.theme.js',
  `// Generated by scripts/build-tokens.mjs — do not edit.
module.exports = {
  colors: ${JSON.stringify({ ...flatten('', color) }, null, 2)},
  spacing: ${JSON.stringify(space, null, 2)},
  borderRadius: ${JSON.stringify(radius, null, 2)},
};
`
);

function flatten(prefix, obj, out = {}) {
  for (const [k, v] of Object.entries(obj)) {
    const key = prefix ? `${prefix}-${k}` : k;
    if (typeof v === 'string') out[key] = v;
    else if (Array.isArray(v)) v.forEach((x, i) => (out[`${key}-${i + 1}`] = x));
    else if (v && typeof v === 'object') flatten(key, v, out);
  }
  return out;
}

/* ---- Swift ---- */
const swiftLines = Object.entries(flatten('', color))
  .map(([k, v]) => `    static let ${camel(k)} = ${swiftColor(v)}`)
  .join('\n');

/** rgba() has to become an sRGB initialiser — Color(hex:) cannot parse it. */
function swiftColor(v) {
  if (v.startsWith('#')) return `Color(hex: "${v}")`;
  const m = v.match(/rgba?\(([^)]+)\)/);
  if (!m) return 'Color.clear';
  const [r, g, b, a = '1'] = m[1].split(',').map((x) => parseFloat(x));
  const f = (x) => (x / 255).toFixed(4);
  return `Color(.sRGB, red: ${f(r)}, green: ${f(g)}, blue: ${f(b)}, opacity: ${parseFloat(a)})`;
}
writeFileSync(
  'tokens/ROUNDSTokens.swift',
  `// Generated by scripts/build-tokens.mjs — do not edit.
// Used by the Live Activity, the widgets and the Watch app so the native
// surfaces cannot drift from the app.
import SwiftUI

public enum ROUNDS {
  public enum Colors {
${swiftLines}
  }
  public enum Radius {
${Object.entries(radius).map(([k, v]) => `    static let ${k} = CGFloat(${v})`).join('\n')}
  }
  public enum Space {
${Object.entries(space).map(([k, v]) => `    static let ${k} = CGFloat(${v})`).join('\n')}
  }
  /// Corner smoothing 0.6 — use RoundedRectangle(cornerRadius:style:.continuous)
  public static let cornerSmoothing = ${geometry.cornerSmoothing}
}
`
);

/* ---- Kotlin ---- */
writeFileSync(
  'tokens/RoundsTokens.kt',
  `// Generated by scripts/build-tokens.mjs — do not edit.
package app.rounds.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object RoundsColors {
${Object.entries(flatten('', color)).map(([k, v]) => `    val ${camel(k)} = Color(${androidColor(v)})`).join('\n')}
}

object RoundsRadius {
${Object.entries(radius).map(([k, v]) => `    val ${k} = ${v}.dp`).join('\n')}
}

object RoundsSpace {
${Object.entries(space).map(([k, v]) => `    val ${k} = ${v}.dp`).join('\n')}
}
`
);

function camel(s) {
  return s.replace(/[-/](\w)/g, (_, c) => c.toUpperCase()).replace(/^(\w)/, (_, c) => c.toLowerCase());
}
function androidColor(v) {
  if (v.startsWith('#')) {
    const hex = v.slice(1);
    return `0xFF${hex.toUpperCase()}`;
  }
  const m = v.match(/rgba?\(([^)]+)\)/);
  if (!m) return '0xFFFFFFFF';
  const [r, g, b, a = '1'] = m[1].split(',').map((x) => parseFloat(x));
  const A = Math.round(parseFloat(a) * 255).toString(16).padStart(2, '0');
  const hex = [r, g, b].map((x) => Math.round(x).toString(16).padStart(2, '0')).join('');
  return `0x${A.toUpperCase()}${hex.toUpperCase()}`;
}

console.log('Wrote tokens/tokens.json, nativewind.theme.js, ROUNDSTokens.swift, RoundsTokens.kt');
